apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque  # normal type for key value storeage
data:
    mongo-root-username: dXNlcm5hbWU=  # base64 encoded username
    mongo-root-password: cGFzc3dvcmQ=
